FROM openjdk:17-alpine

ARG PORT
ENV PORT=$PORT

ARG RABBITMQ_ADDRESSES
ENV RABBITMQ_ADDRESSES=$RABBITMQ_ADDRESSES

ARG DIRECT_CHAT_EXCHANGE_NAME
ENV DIRECT_CHAT_EXCHANGE_NAME=$DIRECT_CHAT_EXCHANGE_NAME

ARG GROUP_CHAT_EXCHANGE_NAME
ENV GROUP_CHAT_EXCHANGE_NAME=$GROUP_CHAT_EXCHANGE_NAME

ARG USER
ENV USER=$USER

ARG GROUPS
ENV GROUPS=$GROUPS

WORKDIR /app
COPY target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]
